env:
  global:
  - secure: hyGRkjsrWNnIXw1bx6t6n9pt7CSh1GEoqgSobppomYLIE4YetbZpHnXt0RzfrROKNiEkuURdYKyX0DQagsWQEdvanVRoKVuySab/XrMcTpx9ve2v/Yy57RSgobQ8bE/svGS/g/IW4I/ewMe3tU3csriQDchmij4TLb/wQWRZlibAw7gy+5iPFLelQV9ssrNckqjoM3f613IxPZSOLpjmqsOP0VaIdo0MmSkztvUU8oTz/JtRH1n/d2CgjfVZ2PVGJTdyTxVJZAxL8TVEMc6AYGAyUPsxUWe6MEfTlm/szuey6pCoZuEsApH4cJr0aW+FvLsSzYOuwzjkgdApxgWB7DSu6RFO++IZ0F3Oxf8kavjvnma6BNsGq5A88iIURM6i1/3vdd5j9T0WVJ8dz39S4a+kONdfV6QRKX5JgNkJxm+3t0ebzG0Ez4dnefY334TbLvL52lpZuX+cOoX68kUgfmMiQB17OP8sgXd1OAIv4wmBLca6bzrRLtcQaJ9HEtP3/V7cJMSz5OPOoN1sXRmTCC79J7uAgPt8KAOjvTpKMhgFN0z3NOirLOMUyoEFmtTzCbUK7ivZjAxmJWw5BEzYe9usd4JluUDu9FOOKxMfSQhsJpwM+FtgQE+UEdSm6V2pX6whT94bluyVSp+tsog6SDc5+xaRlWPfn6LV1GmgOTQ=
  - secure: 1ACwDIRqfHtb26iilYC0ewE4pZoxbfeKuHSQM58DZ4qoMXNds4+mT0qR+eqqg9QBrooVIw+LID/KbLqaHkr+Ou6gRp2beDJmkNWM37ATFfVwq5AbWPA7ONqY1z9/d89gsC48pAhxEU/c8H8G2ysUEai6m4MPj0EhTUQxNeTTYsieTnd2Aj6SCqzl+rcdx5w0KU6MhwJzxTiNUBm1x66ZLCg5ecvbbySOehl6bESlbc7mCn3PgFx4r3f24OQeUsuz7hm9gvjLUcBWwwZoC0z7Cst3LjZPv3QHzDH30/+EI9Bhr3oV1xk4KBAsuX/GYSEVtIuqfqnpGrpMFVIxC/h59K23EmmJJAi+FI02yS6UwTttykws/+VEsuYLqKyoeC9OSn0bhOGji9iAT0ECnfL+F+Fq12CwMOjH8uuUbn0So+0wlH16s2qniEavobeQVJwQvfmD05egvJRS0s7XbxKmAW2Iq4KdBqJFJkuRG6Shp++cyvx3GR5LZmyG3FxB394tuRwg7I3iWa2m0UQZcFrHb0znbH0qLLqTlKfMiYlLikaTVJacPbagSoFfu3dnHtMnlh7RakHZv/lXL6L5//F10KuCCH+wNrGEbZjA9bji94+jJGHqqK5OS2A8z0K86vfRBSdorJyTsov63d2kJDMxfb+hdZL+2027GIKueHG4rwE=
  - MANAGER_SH="release-manager.sh"
  - MANAGER_URL="https://raw.githubusercontent.com/3mdeb/docker-release-manager/master/release-manager.sh"
sudo: required
services:
- docker
before_script:
- wget -O $MANAGER_SH $MANAGER_URL
script:
- bash $MANAGER_SH build
after_script:
- docker images
deploy:
  skip_cleanup: true
  provider: script
  script: bash $MANAGER_SH push
  on:
    branch: master
