name: Build fwdump-docker container
on:
  push:
    branches:
      - '**'        # matches every branch
  create:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - '**'        # matches every branch


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        if: github.event_name != 'create' && !contains(github.ref, 'refs/tags/')
        with:
          context: .
          push: false
      -
        name: Build and push
        uses: docker/build-push-action@v2
        if: github.event_name == 'create' && contains(github.ref, 'refs/tags/')
        with:
          context: .
          push: true
          tags: '3mdeb/fwdump-docker:${{github.ref_name}}'
